services:
  chisel-server:
    image: jpillora/chisel:latest
    container_name: chisel-server
    restart: unless-stopped
    command: >
      server
      --reverse
      --auth ${CHISEL_AUTH}
      --port 4016
    ports:
      - "4016:4016"
      - "4015:4015"
      - "4014:4014"
